defaults:
  - _self_
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: maximize
    study_name: tuning_experiment
    storage: 'sqlite:///db/tuning_experiment.db'
    n_trials: 3
    n_jobs: 1
    custom_search_space: tune.configure

params:
  n_estimators:
    type: int
    low: 100
    high: 500
  max_depth:
    type: int
    low: 5
    high: 25
  min_samples_split:
    type: int
    low: 2
    high: 20
  min_samples_leaf:
    type: int
    low: 1
    high: 20
  max_features:
    type: str
    choices: ['sqrt', None]

model:
  _target_: sklearn.ensemble.ExtraTreesClassifier
  n_estimators: 100
  max_depth: 1
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: 'sqrt'
  random_state: 666
  bootstrap: true

objective:
  _target_: tune.evaluate_model